### ISSUE TITLE
error TS2304: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by bdedardel** [HerringtonDarkholme/vue-ts-example#1]
Hi,

Thanks for this example.
Unfortunatelly, I get an error:

```
$ ./node_modules/typescript/bin/tsc app.ts 
node_modules/vue/types/options.d.ts(12,6): error TS2304: Cannot find name 'Promise'.
```

**Comment by bdedardel** [comment]
Fix:
- install typings

```
$ npm install -g typings
$ typings install dt~es6-promise dt~es6-collections --global --save
```
- add /// &lt;reference path="typings/index.d.ts" /&gt; in app.ts

```
/// <reference path="typings/index.d.ts" />
declare var require: any

import Vue = require('vue')
var App = require('./app.vue').default

new Vue({
  el: '#app',
  components: { App },
  render: h => h('app')
})

```

**Comment by m0uneer** [comment]
Highly recommended to use npm module instead of deprecated "typings"
```
$ npm install --save-dev @types/es6-promise
$ npm install --save-dev @types/es6-collections
```

**Comment by HerringtonDarkholme** [comment]
> node_modules/vue/types/options.d.ts(12,6): error TS2304: Cannot find name 'Promise'.

Hi, this is not intended. Since I have added `es2015.promise` in tsconfig.json. If you want compiling single file, you need to add `--lib` option.
